FROM python:3.12-slim

WORKDIR /app

RUN pip install gunicorn==20.1.0

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["python manage.py migrate --noinput && python manage.py collectstatic --clear --noinput && gunicorn --bind 0.0.0.0:8000 weeek_django.wsgi:application"]