# Generated by Django 5.2.6 on 2025-09-09 03:27

import django.db.models.deletion
import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="priority",
            name="value",
            field=models.IntegerField(
                default=1, unique=True, verbose_name="ID в API WEEEK"
            ),
            preserve_default=False,
        ),
    ]
