# Generated by Django 5.2.6 on 2025-09-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_assignee_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='week_key',
            field=models.CharField(max_length=512, null=True, verbose_name='WeekApiKey'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='api_key',
            field=models.CharField(max_length=512, null=True, verbose_name='TgBotApiKey'),
        ),
    ]
