# Generated by Django 5.2.6 on 2025-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settings_week_key_alter_settings_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMoveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_id', models.CharField(max_length=100)),
                ('from_column', models.CharField(max_length=255)),
                ('to_column', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('move_time', models.DateTimeField()),
                ('time_spent', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.DeleteModel(
            name='Assignee',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
