# Generated by Django 5.2.6 on 2025-09-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_taskmovelog_remove_task_assignee_delete_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmovelog',
            name='board_name',
            field=models.CharField(default=123),
            preserve_default=False,
        ),
    ]
