# Generated by Django 5.2.6 on 2025-09-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_taskmovelog_board_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
