# Generated by Django 5.2.6 on 2025-09-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_delete_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmovelog',
            name='user',
        ),
    ]
